# Modified from https://github.com/libgdx/libgdx/blob/master/.github/workflows/build-publish.yml

name: Build Documentation

on:
  workflow_dispatch:
    branches:
      - main
  push:
    paths:
      - 'docs/**'
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: |
          export NDK_HOME=$ANDROID_NDK_LATEST_HOME
          ./gradlew jniGen
      - name: All Javadoc
        run: |
          ./gradlew allJavadoc
      - name: Moving Javadoc
        run: |
          mv build/docs/javadoc docs/public/
      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false
      - name: Build VitePress
        run: |
          cd docs
          pnpm install
          pnpm docs:build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/.vitepress/dist
          single-commit: true
